# Generated by Django 5.0.1 on 2024-01-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='health_conditions/images/')),
                ('facts', models.TextField()),
                ('symptoms', models.TextField()),
                ('causes', models.TextField()),
                ('diagnosis', models.TextField()),
                ('treatments', models.TextField()),
                ('complications', models.TextField()),
                ('prevention', models.TextField()),
                ('nutrition', models.TextField()),
                ('alphabet', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
