# Generated by Django 5.0.1 on 2024-01-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('category', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('rating', models.FloatField(default=0.0)),
                ('verified', models.BooleanField(default=False)),
                ('companyName', models.CharField(max_length=255)),
                ('offer_start_date', models.DateField()),
                ('offer_end_date', models.DateField()),
                ('postedby', models.CharField(max_length=255)),
                ('reelImage', models.ImageField(upload_to='products/reels/')),
                ('reelStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
